# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8 
      
    working_directory: ~/repo

    steps:
      - checkout

      # inject env vars
      - run:
          name: sed
          command: sed -i "" -e "s|^const ES_URL.*|const ES_URL = 'https://elasticsearch.developers.italia.it/indicepa/_search';|g"  ../public/assets/js/constants.js

      # npm build 
      - run: 
          name: npm install 
          command: npm install
      - run:
          name: npm lint 
          command: npm run lint

workflows:
  version: 2
  continuous-deploy:
    jobs:
      - build:
          filters:
            branches:
                only:
                  - master

