# Javascript Node CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: italia/developers-italia-onboarding
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  build:
    docker:
      - image: circleci/node:8

    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: npm install
          command: npm install
      - run:
          name: npm lint
          command: npm run lint
  docker-build-prod:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:latest .
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  docker-build-dev:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:development .
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  deploy-prod:
    machine:
      enabled: true
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: scp /tmp/workspace/image.tar circleci@$SSH_HOST:/tmp/image.tar
      - run:
          name: deploy on prod
          command: |
            ssh circleci@$SSH_HOST $SSH_COMMAND_PROD
  deploy-dev:
    machine:
      enabled: true
    steps:
      - attach_workspace:
          at: /tmp/workspace
      #- run: scp /tmp/workspace/image.tar circleci@$SSH_HOST:/tmp/image.tar
      - run: rsync -avz /tmp/workspace/image.tar circleci@$SSH_HOST:/tmp/image.tar
      - run:
          name: deploy on dev
          command: |
            ssh circleci@$SSH_HOST $SSH_COMMAND_DEV

workflows:
  version: 2
  on-commit-test:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - development
                - master
  on-commit-build-and-deploy_prod:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - docker-build-prod:
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - deploy-prod:
          requires:
            - build
            - docker-build-prod
          filters: 
            branches:
              only:
                - master
  on-commit-build-and-deploy_dev:
    jobs:
      - build:
          filters:
            branches:
              only:
                - development
      - docker-build-dev:
          requires:
            - build
          filters:
            branches:
              only:
                - development
      - deploy-dev:
          requires:
            - build
            - docker-build-dev
          filters:
            branches:
              only:
                - development
